# Generated by Django 4.2.30 on 2026-05-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="matricule",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
