# Generated by Django 4.2.30 on 2026-06-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "academique",
            "0004_filiere_niveau_matiere_credits_alter_matiere_avec_cc_and_more",
        ),
        ("authentification", "0002_utilisateur_is_registered_utilisateur_matricule"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etudiants",
                to="academique.niveau",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etudiants",
                to="academique.option",
            ),
        ),
    ]
