# Generated by Django 4.2.30 on 2026-05-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("coefficient", models.PositiveSmallIntegerField(default=1)),
                (
                    "enseignant",
                    models.ForeignKey(
                        limit_choices_to={"role": "enseignant"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matieres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("actif", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("lun", "Lundi"),
                            ("mar", "Mardi"),
                            ("mer", "Mercredi"),
                            ("jeu", "Jeudi"),
                            ("ven", "Vendredi"),
                            ("sam", "Samedi"),
                        ],
                        max_length=3,
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("salle", models.CharField(max_length=50)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academique.matiere",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academique.semestre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_cc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "note_examen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "note_finale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("valide", models.BooleanField(default=False)),
                (
                    "etudiant",
                    models.ForeignKey(
                        limit_choices_to={"role": "etudiant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="academique.matiere",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="academique.semestre",
                    ),
                ),
            ],
            options={
                "unique_together": {("etudiant", "matiere", "semestre")},
            },
        ),
    ]
