# Generated by Django 4.2.30 on 2026-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="avec_cc",
            field=models.BooleanField(
                default=True, help_text="Cette matière a un contrôle continu"
            ),
        ),
    ]
