# Generated by Django 4.2.30 on 2026-05-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0002_matiere_avec_cc"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploiDuTempsExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_examen",
                    models.CharField(
                        choices=[
                            ("partiel", "Partiel / CC"),
                            ("examen", "Examen Final"),
                        ],
                        default="examen",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("salle", models.CharField(max_length=50)),
                ("observations", models.TextField(blank=True)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens",
                        to="academique.matiere",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens",
                        to="academique.semestre",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "heure_debut"],
            },
        ),
    ]
