# Generated by Django 4.2.30 on 2026-06-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0003_emploidutempsexamen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("MI", "Mathématiques-Informatique"),
                            ("PC", "Physique-Chimie"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                        ],
                        max_length=5,
                    ),
                ),
                ("credits_requis", models.PositiveSmallIntegerField(default=60)),
                (
                    "credits_requis_passage",
                    models.PositiveSmallIntegerField(
                        default=48,
                        help_text="Crédits minimum pour passer à l'année suivante",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux",
                        to="academique.filiere",
                    ),
                ),
            ],
            options={
                "unique_together": {("filiere", "code")},
            },
        ),
        migrations.AddField(
            model_name="matiere",
            name="credits",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="Nombre de crédits ECTS"
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="avec_cc",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("MATH_FOND", "Mathématiques Fondamentales"),
                            ("STAT", "Statistique"),
                            ("INFO", "Informatique"),
                            ("PHYSIQUE", "Physique"),
                            ("CHIMIE", "Chimie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="academique.niveau",
                    ),
                ),
            ],
            options={
                "unique_together": {("niveau", "code")},
            },
        ),
        migrations.AddField(
            model_name="matiere",
            name="niveau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matieres",
                to="academique.niveau",
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matieres",
                to="academique.option",
            ),
        ),
    ]
