# Generated by Django 4.2.30 on 2026-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academique",
            "0004_filiere_niveau_matiere_credits_alter_matiere_avec_cc_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiere",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
