# Generated by Django 4.2.30 on 2026-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academique", "0005_alter_filiere_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="niveau",
            name="code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="credits_requis_passage",
            field=models.PositiveSmallIntegerField(default=48),
        ),
        migrations.AlterField(
            model_name="option",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
